2022-05-08 23:59:42,649 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-08 23:59:42,661 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652034577602"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1651968000000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652054376819"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: PING FAILED for datasource: StorePrimary - this datasource is offline.&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652054376819"/></dao></FailedPersistence>
2022-05-08 23:59:42,684 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@a48abdeObject Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 18:29:37.602 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-08 00:00:00.0 logLevel=WARN logTimestamp=2022-05-08 23:59:36.819 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: PING FAILED for datasource: StorePrimary - this datasource is offline.</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-08 23:59:36.819  No Available Datasources.
2022-05-08 23:59:42,684 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652034577602"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1651968000000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652054376819"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: PING FAILED for datasource: StorePrimary - this datasource is offline.&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652054376819"/></dao></FailedPersistence>
2022-05-08 23:59:51,556 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-08 23:59:51,556 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652034591555"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1651968000000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652054391555"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652054391555"/></dao></FailedPersistence>
2022-05-08 23:59:51,556 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@289a5e71Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 18:29:51.555 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-08 00:00:00.0 logLevel=WARN logTimestamp=2022-05-08 23:59:51.555 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>Local</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-08 23:59:51.555  No Available Datasources.
2022-05-08 23:59:51,561 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652034591555"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1651968000000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652054391555"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;Local&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652054391555"/></dao></FailedPersistence>
